# Site
repository: anderhau/anderhau.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexandre Y. Hau Hang Sang
#title: 
email: alexandre.hau@outlook.com
website: anderhau.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: sashahau
github_username:  anderhau
#instagram_username: 
#linkedin_username:
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: anderhau.github.io
  icon: fas fa-globe
  url: https://anderhau.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an early career professional with a Business degree. Experienced in relationship management with proven leadership and communication skills. Managed portfolio of international clients and prospect relationships to maximize net contribution through an emphasis on maintaining quality service for all customers and expanding existing relationships. I am looking to secure a challenging role where I can utilize my skills and add value to the business.
  
  I am fluent in both: <mark>English</mark> and <mark>French</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pacific Prime
        link: https://pacificprime.cn/en/
        # link_text: https://pacificprime.cn/en/
        sub_title: Relationship Manager (Beijing Office)
        caption: December 2019 – April 2020
        quote: >
          Founded in 1999, Pacific Prime has grown to be one of the largest insurance intermediaries in Asia with offices in Hong Kong, Singapore, Thailand, Shanghai and Beijing. Pacific Prime has over 120,000 clients in over 130 countries.
          
        description: | # this will include new lines to allow paragraphs
            - Advise on renewal of insurance and offer alternatives with a focus on client experience and risk management
            - Aim to preserve client portfolio and improve client retention
            - Maintain knowledge on all complex policies and coverage details
            - Develop new referrals and create new lead for the sales team through my existing clients.
            
      - layout: left   
        title: 
        link: https://pacificprime.cn/en/
        # link_text: https://pacificprime.cn/en/
        sub_title: Consultant (Beijing Office)
        caption: February 2019 – November 2019
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            - Delivering comprehensive insurance products and solutions tailored to the needs of the client.
            - Maintain knowledge on all complex policies and coverage details and assist customers to complete all applications and forms and all required documents.
            - Meet or exceed sales targets, understand and meet multiple performance metrics
            
      - layout: left   
        title: DTOS Ltd
        link: https://www.dtos-mu.com/
        # link_text: https://www.dtos-mu.com/
        sub_title: Corporate Administrator
        caption: October 2017 – October 2018
        quote: > 
            For more than 27 years, DTOS has been assisting the international business community in structuring their investment vehicle for investment into Africa, Asia and other parts of the world.
          
        description: | # this will include new lines to allow paragraphs
            - To assist in the provision of corporate services, including the formation of companies, submission of statutory filings, company secretarial services such as the keeping of minutes and registers, and other ancillary activities
            - To collect due diligence documentation and prepare engagement letters
            - To assist with administrative tasks relating to corporate structures and regulatory license applications
            - To carry out any other ad hoc assignments related to specific regulatory and supervisory issues that may arise from time to time and to report on the outcome of such assignments as may be appropriate and necessary.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Monash University
        caption: 2011 - 2016
          - sub_title: Bachelor of Business and Commerce
            title: Major in Economics and International Business
        quote: >
          Established in 1998, Monash University Malaysia is the third largest campus of Australia's largest university and the first foreign university campus in Malaysia. Monash University is a premier research-intensive Australian university ranked among the top 100 universities in the world by the Times Higher Education World University Rankings, and a member of Australia’s prestigious Group of Eight (Go8). Monash University is also ranked 58 in the QS 2022 World University Rankings.
          
        description: | # this will include new lines to allow paragraphs
          During my time at Monash I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as the project manager of the *Monash Accounting & Finance Club*.
       
  - title: Interests # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Web Development
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I started this website as a way if learning Web development and it has since grown into a fully functional website. I have learned many skills through this and been I'm very proud of having this in my skillset.
        description: | # this will include new lines to allow paragraphs
          # text
          
      - layout: left
        title: Data Analytics
        sub_title: Google Data Analytics Professional Certificate
        link: https://coursera.org/share/78613ec761445e0bc4b4277c32fb1133
        link_text: Foundations: Data, Data, Everywhere 
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          # text
        description: | # this will include new lines to allow paragraphs
          # text
          
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
